import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class QueryService {
  constructor() {}

  filterToggle(): void {
    // $(document).on('click', '#filter_search', function() {
    //   $('#filter_search').toggleClass("setclose");
    // });
  }

  public countryList = [
    {
      CountryName: 'China',
      Region: 'Beijing',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'USA',
      Region: 'Newyork',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'Athens',
      Region: 'Greece',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'Thailand',
      Region: 'Bangkok',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'Phuket island	',
      Region: 'Mueang Phuket',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'Germany',
      Region: 'Berlin',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'Angola',
      Region: 'Luanda',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'Albania',
      Region: 'Albania',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'Turkey',
      Region: 'Ankara',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'Phuket island',
      Region: 'Mueang Phuket',
      isSelected: false,
      isStatus: false,
    },
    {
      CountryName: 'Germany',
      Region: 'Berlin',
      isSelected: false,
    },
    {
      CountryName: 'Angola',
      Region: 'Luanda',
      isSelected: false,
    },
    {
      CountryName: 'Albania',
      Region: 'Albania',
      isSelected: false,
    },
    {
      CountryName: 'Turkey',
      Region: 'Ankara',
      isSelected: false,
    },
  ];

  public expenseCategoryList = [
    {
      Date: '2/27/2022',
      Categoryname: 'Employee Benefits',
      Reference: 'PT001',
      Status: 'Active',
      Amount: '120',
      isSelected: false,
      Description: 'Employee Vehicle',
    },
    {
      Date: '1/15/2022	',
      Categoryname: 'Foods & Snacks	',
      Reference: 'PT002',
      Status: 'Active',
      Amount: '250',
      isSelected: false,
      Description: 'Employee Foods',
    },
    {
      Date: '3/24/2022',
      Categoryname: 'Entertainment',
      Reference: 'PT003',
      Status: 'In Active',
      Amount: '120',
      isSelected: false,
      Description: 'Office Vehicle',
    },
    {
      Date: '1/15/2022	',
      Categoryname: 'Office Expenses & Postage	',
      Reference: 'PT004',
      Status: 'Active',
      Amount: '320',
      isSelected: false,
      Description: 'Employee Foods',
    },
    {
      Date: '2/27/2022',
      Categoryname: 'Employee Benefits',
      Reference: 'PT005',
      Status: 'Active',
      Amount: '250',
      isSelected: false,
      Description: 'Employee Vehicle',
    },
    {
      Date: '1/15/2022	',
      Categoryname: 'Foods & Snacks	',
      Reference: 'PT006',
      Status: 'Active',
      Amount: '250',
      isSelected: false,
      Description: 'Employee Foods',
    },
    {
      Date: '3/24/2022',
      Categoryname: 'Entertainment',
      Reference: 'PT007',
      Status: 'In Active',
      Amount: '120',
      isSelected: false,
      Description: 'Office Vehicle',
    },
    {
      Date: '1/15/2022	',
      Categoryname: 'Office Expenses & Postage	',
      Reference: 'PT008',
      Status: 'Active',
      Amount: '320',
      isSelected: false,
      Description: 'Employee Foods',
    },
    {
      Date: '2/27/2022',
      Categoryname: 'Employee Benefits',
      Reference: 'PT009',
      Status: 'Active',
      Amount: '120',
      isSelected: false,
      Description: 'Employee Vehicle',
    },
    {
      Date: '1/15/2022	',
      Categoryname: 'Foods & Snacks	',
      Reference: 'PT010',
      Status: 'Active',
      Amount: '250',
      isSelected: false,
      Description: 'Employee Foods',
    },
    {
      Date: '3/24/2022',
      Categoryname: 'Entertainment',
      Reference: 'PT011',
      Status: 'In Active',
      Amount: '120',
      isSelected: false,
      Description: 'Office Vehicle',
    },
    {
      Date: '1/15/2022	',
      Categoryname: 'Office Expenses & Postage	',
      Reference: 'PT012',
      Status: 'Active',
      Amount: '320',
      isSelected: false,
      Description: 'Employee Foods',
    },
  ];

  public expenseList = [
    {
      Categoryname: 'Employee Benefits',
      Reference: 'PT001',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'Active',
      Amount: '120',
      Description: 'Employee Vehicle',
    },
    {
      Categoryname: 'Foods & Snacks	',
      Reference: 'PT002',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'Active',
      Amount: '250',
      Description: 'Employee Foods',
    },
    {
      Categoryname: 'Entertainment',
      Reference: 'PT003',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'In Active',
      Amount: '120',
      Description: 'Office Vehicle	',
    },
    {
      Categoryname: 'Office Expenses & Postage	',
      Reference: 'PT004',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'Active',
      Amount: '320',
      Description: 'Employee Foods',
    },
    {
      Categoryname: 'Employee Benefits',
      Reference: 'PT005',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'Active',
      Amount: '250',
      Description: 'Employee Vehicle',
    },
    {
      Categoryname: 'Foods & Snacks',
      Reference: 'PT006',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'Active',
      Amount: '250',
      Description: 'Employee Foods',
    },
    {
      Categoryname: 'Entertainment',
      Reference: 'PT007',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'In Active',
      Amount: '120',
      Description: 'Office Vehicle',
    },
    {
      Categoryname: 'Office Expenses & Postage',
      Reference: 'PT008',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'Active',
      Amount: '320',
      Description: 'Employee Foods	',
    },
    {
      Categoryname: 'Employee Benefits',
      Reference: 'PT009',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'Active',
      Amount: '120',
      Description: 'Employee Vehicle	',
    },
    {
      Categoryname: 'Foods & Snacks',
      Reference: 'PT010',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'Active',
      Amount: '250',
      Description: 'Employee Foods',
    },
    {
      Categoryname: 'Entertainment',
      Reference: 'PT011',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'In Active',
      Amount: '120',
      Description: 'Office Vehicle',
    },
    {
      Categoryname: 'Office Expenses & Postage',
      Reference: 'PT012',
      Date: '19 Nov 2022',
      isSelected: false,
      Status: 'Active',
      Amount: '320',
      Description: 'Employee Foods	',
    },
  ];
  public customerList = [
    {
      img: 'assets/img/customer/customer1.jpg',
      CustomerName: 'Thomas',
      code: '201',
      Customer: 'Thomas',
      Phone: '+12163547758',
      email: 'thomas@example.com',
      isSelected: false,
      Country: 'USA',
    },
    {
      img: 'assets/img/customer/customer2.jpg',
      CustomerName: 'Benjamin',
      code: '202',
      Customer: 'Benjamin',
      Phone: '123-456-888',
      email: 'customer@example.com	',
      isSelected: false,
      Country: 'USA',
    },
    {
      img: 'assets/img/customer/customer2.jpg',
      CustomerName: 'James',
      code: '521',
      Customer: '	James',
      Phone: '123-456-888',
      email: 'customer@example.com	',
      isSelected: false,
      Country: 'USA',
    },
    {
      img: 'assets/img/customer/customer3.jpg',
      CustomerName: 'Bruklin',
      code: '555',
      Customer: '	Bruklin',
      Phone: '123-456-888',
      email: 'bruklin@example.com',
      isSelected: false,
      Country: 'Thailand',
    },
    {
      img: 'assets/img/customer/customer3.jpg',
      CustomerName: 'Beverly',
      code: '325',
      Customer: '	Beverly',
      Phone: '+12163547758',
      email: 'Beverly@example.com',
      isSelected: false,
      Country: 'Phuket island',
    },
    {
      img: 'assets/img/customer/customer4.jpg',
      CustomerName: 'B. Huber',
      code: '589',
      Customer: '	B. Huber',
      Phone: '123-456-888',
      email: 'Huber@example.com',
      isSelected: false,
      Country: 'Germany',
    },
    {
      img: 'assets/img/customer/customer5.jpg',
      CustomerName: 'James Stawberry',
      code: '254',
      Customer: '	James Stawberry	',
      Phone: '+12163547758',
      email: 'customer@example.com',
      isSelected: false,
      Country: 'Angola',
    },
    {
      img: 'assets/img/customer/customer3.jpg',
      CustomerName: 'James Stawberry',
      code: '681',
      Customer: '	Fred john	',
      Phone: '123-456-888',
      email: 'john@example.com	',
      isSelected: false,
      Country: 'Albania',
    },
    {
      img: 'assets/img/customer/customer5.jpg',
      CustomerName: 'B. Huber',
      code: '589',
      Customer: '	B. Huber',
      Phone: '123-456-888',
      email: 'Huber@example.com',
      isSelected: false,
      Country: 'Germany',
    },
    {
      img: 'assets/img/customer/customer6.jpg',
      CustomerName: 'James Stawberry',
      code: '254',
      Customer: '	James Stawberry	',
      Phone: '+12163547758',
      email: 'customer@example.com',
      isSelected: false,
      Country: 'Angola',
    },
    {
      img: 'assets/img/customer/customer3.jpg',
      CustomerName: 'James Stawberry',
      code: '681',
      Customer: '	Fred john	',
      Phone: '123-456-888',
      email: 'john@example.com	',
      isSelected: false,
      Country: 'Albania',
    },
    {
      img: 'assets/img/customer/customer5.jpg',
      CustomerName: 'B. Huber',
      code: '589',
      Customer: '	B. Huber',
      Phone: '123-456-888',
      email: 'Huber@example.com',
      isSelected: false,
      Country: 'Germany',
    },
    {
      img: 'assets/img/customer/customer6.jpg',
      CustomerName: 'James Stawberry',
      code: '254',
      Customer: '	James Stawberry	',
      Phone: '+12163547758',
      email: 'customer@example.com',
      isSelected: false,
      Country: 'Angola',
    },
    {
      img: 'assets/img/customer/customer3.jpg',
      CustomerName: 'James Stawberry',
      code: '681',
      Customer: '	Fred john	',
      Phone: '123-456-888',
      email: 'john@example.com	',
      isSelected: false,
      Country: 'Albania',
    },
  ];
  public userList = [
    {
      Username: 'Thomas',
      Phone: '+12163547758',
      email: 'thomas@example.com',
      isSelected: false,
      Role: 'Admin',
      CreatedOn: '3/15/2022',
      Status: 'Active',
      Permissions:4
    },

    {
      Username: 'Bruklin2022',
      Phone: '+123-456-888	',
      email: 'bruklin@example.com	',
      isSelected: false,
      Role: 'Delivery Biker	',
      CreatedOn: '2/27/2022',
      Status: 'Active',
      Permissions:7
    },
    {
      Username: 'BeverlyWIN25',
      Phone: '+12163547758	',
      email: 'bruklin@example.com	',
      isSelected: false,
      Role: 'Delivery Biker	',
      CreatedOn: '2/27/2022',
      Status: 'Active',
      Permissions:5
    }
  ];
  public quotationList = [
    {
      ProductName: 'Macbook pro',
      Reference: 'PT001',
      CustmerName: 'walk-in-customer	',
      isSelected: false,
      Status: 'Sent',
      GrandTotal: '550',
      img: 'assets/img/product/product1.jpg',
    },
    {
      ProductName: 'Orange',
      Reference: 'PT002',
      CustmerName: 'walk-in-customer	',
      isSelected: false,
      Status: 'Ordered',
      GrandTotal: '410',
      img: 'assets/img/product/product2.jpg',
    },
    {
      ProductName: 'Stawberry',
      Reference: 'PT003',
      CustmerName: 'walk-in-customer',
      isSelected: false,
      Status: 'Pending',
      GrandTotal: '410',
      img: 'assets/img/product/product4.jpg',
    },
    {
      ProductName: 'Avocat',
      Reference: 'PT004',
      CustmerName: 'John Smith',
      isSelected: false,
      Status: 'Sent',
      GrandTotal: '500',
      img: 'assets/img/product/product5.jpg',
    },
    {
      ProductName: 'Macbook Pro',
      Reference: 'PT005',
      CustmerName: 'Beverly',
      isSelected: false,
      Status: 'Pending',
      GrandTotal: '1050',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Apple Earpods',
      Reference: 'PT006',
      CustmerName: 'B. Huber',
      isSelected: false,
      Status: 'Sent',
      GrandTotal: '2530',
      img: 'assets/img/product/product7.jpg',
    },
    {
      ProductName: 'iPhone 11',
      Reference: 'PT007',
      CustmerName: 'Thomas',
      isSelected: false,
      Status: 'Sent',
      GrandTotal: '550',
      img: 'assets/img/product/product8.jpg',
    },
    {
      ProductName: 'samsung',
      Reference: 'PT008',
      CustmerName: 'Benjamin',
      isSelected: false,
      Status: 'Ordered',
      GrandTotal: '550',
      img: 'assets/img/product/product9.jpg',
    },
    {
      ProductName: 'Unpaired gray',
      Reference: 'PT0010',
      CustmerName: 'James',
      isSelected: false,
      Status: 'Pending',
      GrandTotal: '210',
      img: 'assets/img/product/product10.jpg',
    },
    {
      ProductName: 'Apple Earpods',
      Reference: 'PT006',
      CustmerName: 'B. Huber',
      isSelected: false,
      Status: 'Sent',
      GrandTotal: '2530',
      img: 'assets/img/product/product7.jpg',
    },
    {
      ProductName: 'iPhone 11',
      Reference: 'PT007',
      CustmerName: 'Thomas',
      isSelected: false,
      Status: 'Sent',
      GrandTotal: '550',
      img: 'assets/img/product/product8.jpg',
    },
    {
      ProductName: 'samsung',
      Reference: 'PT008',
      CustmerName: 'Benjamin',
      isSelected: false,
      Status: 'Ordered',
      GrandTotal: '550',
      img: 'assets/img/product/product9.jpg',
    },
  ];
  public transferList = [
    {
      Date: '19 Nov 2022',
      Reference: 'TR0101',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '1500.00',
      Status: 'Completed',
    },
    {
      Date: '19 Nov 2022',
      Reference: 'TR0102',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '45000.00',
      Status: 'Completed',
    },
    {
      Date: '19 Nov 2022',
      Reference: 'TR0103',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '2400.00',
      Status: 'Completed',
    },
    {
      Date: '19 Nov 2022',
      Reference: 'TR0104',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '2400.00',
      Status: 'Completed',
    },
    {
      Date: '19 Nov 2022',
      Reference: 'TR0105',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '2400.00',
      Status: 'Completed',
    },
    {
      Date: '19 Nov 2022',
      Reference: 'TR0106',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '8456.00',
      Status: 'Completed',
    },
    {
      Date: '19 Nov 2022',
      Reference: 'TR0107',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '150.00',
      Status: 'Completed',
    },
    {
      Date: '19 Nov 2022',
      Reference: 'TR0108',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '365.00',
      Status: 'Pending',
    },
    {
      Date: '19 Nov 2022',
      Reference: 'TR0109',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '365.00',
      Status: 'Pending',
    },
    {
      Date: '19 Nov 2022',
      isSelected: false,
      Reference: 'TR01010',
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '365.00',
      Status: 'Pending',
    },
    {
      Date: '19 Nov 2022',
      isSelected: false,
      Reference: 'TR01011',
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '365.00',
      Status: 'Pending',
    },
    {
      Date: '19 Nov 2022',
      Reference: 'TR01011',
      isSelected: false,
      From: 'Store1',
      Paid: 'Store2',
      items: '10.00',
      Grandtotal: '365.00',
      Status: 'Pending',
    },
  ];
  public invoiceReport = [
    {
      Invoicenumber: 'INV001',
      Customername: 'Thomas21',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '1500.00',
      Paid: '1500.00',
      Amountdue: '1500.00',
      Status: 'Paid',
    },
    {
      Invoicenumber: 'INV002',
      Customername: '504Benjamin',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Overdue',
    },
    {
      Invoicenumber: 'INV003',
      Customername: 'James 524	',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Overdue',
    },
    {
      Invoicenumber: 'INV004',
      Customername: 'Bruklin2022',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Paid',
    },
    {
      Invoicenumber: 'INV005',
      Customername: 'BeverlyWIN25',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Overdue',
    },
    {
      Invoicenumber: 'INV006',
      Customername: 'BHR256',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Paid',
    },
    {
      Invoicenumber: 'INV007',
      Customername: 'BHR256',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Paid',
    },
    {
      Invoicenumber: 'INV008',
      Customername: 'BHR256',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Unpaid',
    },
    {
      Invoicenumber: 'INV009',
      Customername: 'BHR256',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Unpaid',
    },
    {
      Invoicenumber: 'INV0010',
      Customername: 'BHR256',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Unpaid',
    },
    {
      Invoicenumber: 'INV007',
      Customername: 'BHR256',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Paid',
    },
    {
      Invoicenumber: 'INV008',
      Customername: 'BHR256',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Unpaid',
    },
    {
      Invoicenumber: 'INV009',
      Customername: 'BHR256',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Unpaid',
    },
    {
      Invoicenumber: 'INV0010',
      Customername: 'BHR256',
      isSelected: false,
      Duedate: '29-03-2022',
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Unpaid',
    },
  ];
  public productList = [
    {
      ProductName: 'Macbook pro',
      SKU: 'PT001',
      Category: 'Computers',
      isSelected: false,
      Brand: 'N/D',
      price: '1500.00',
      Unit: 'pc',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product1.jpg',
    },
    {
      ProductName: 'Orange',
      SKU: 'PT002',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'pc',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product2.jpg',
    },
    {
      ProductName: 'Pineapple',
      SKU: 'PT003',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'pc',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product3.jpg',
    },
    {
      ProductName: 'Strawberry',
      SKU: 'PT004',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'pc',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product4.jpg',
    },
    {
      ProductName: 'Avocat',
      SKU: 'PT005',
      Category: '	Accessories',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'pc',
      Qty: '150.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product5.jpg',
    },
    {
      ProductName: 'Macbook Pro',
      SKU: 'PT006',
      Category: '	Shoes',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'pc',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Apple Earpods',
      SKU: 'PT007',
      Category: '	Shoes',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'pc',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product7.jpg',
    },
    {
      ProductName: 'iPhone 11',
      SKU: 'PT008',
      Category: '	Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'pc',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product8.jpg',
    },
    {
      ProductName: 'samsung',
      SKU: 'PT009',
      Category: '	Earphones',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'pc',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product9.jpg',
    },
    {
      ProductName: 'Banana',
      SKU: 'PT0010',
      Category: '	Health Care',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'kg',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product11.jpg',
    },
    {
      ProductName: 'Limon',
      SKU: 'PT0011',
      Category: '	Health Care',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'kg',
      Qty: '100.00',
      CreatedBy: 'Admin',
      img: 'assets/img/product/product17.jpg',
    },
  ];
  public categoryList = [
    {
      img: 'assets/img/product/product6.jpg',
      Categoryname: 'Computers',
      CategoryCode: '	CT001',
      isSelected: false,
      Description: 'Computers Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product3.jpg',
      Categoryname: 'Fruits',
      CategoryCode: '	CT002',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product2.jpg',
      Categoryname: 'Fruits',
      CategoryCode: '	CT003',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product3.jpg',
      Categoryname: 'Fruits',
      CategoryCode: '	CT004',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product6.jpg',
      Categoryname: 'Accessories',
      CategoryCode: '	CT005',
      isSelected: false,
      Description: 'Accessories Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product8.jpg',
      Categoryname: 'Accessories',
      CategoryCode: '	CT006',
      isSelected: false,
      Description: 'Accessories Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product9.jpg',
      Categoryname: 'Accessories',
      CategoryCode: '	CT007',
      isSelected: false,
      Description: 'Accessories Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product1.jpg',
      Categoryname: 'Accessories',
      CategoryCode: '	CT008',
      isSelected: false,
      Description: 'Accessories Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product7.jpg',
      Categoryname: 'Accessories',
      CategoryCode: '	CT009',
      isSelected: false,
      Description: 'Accessories Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product10.jpg',
      Categoryname: 'Accessories',
      CategoryCode: '	CT0010',
      isSelected: false,
      Description: 'Accessories Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product6.jpg',
      Categoryname: 'Accessories',
      CategoryCode: '	CT008',
      isSelected: false,
      Description: 'Accessories Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product9.jpg',
      Categoryname: 'Accessories',
      CategoryCode: '	CT009',
      isSelected: false,
      Description: 'Accessories Description',
      CreatedBy: '	Admin',
    },
    {
      img: 'assets/img/product/product1.jpg',
      Categoryname: 'Accessories',
      CategoryCode: '	CT0010',
      isSelected: false,
      Description: 'Accessories Description',
      CreatedBy: '	Admin',
    },
  ];
  public subcategoryList = [
    {
      Image: 'assets/img/product/product1.jpg',
      Category: 'Computers',
      Parentcategory: 'Computers',
      CategoryCode: 'CT001',
      isSelected: false,
      Description: 'Computers Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product2.jpg',
      Category: 'Fruits',
      Parentcategory: 'Fruits',
      CategoryCode: 'CT002',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product3.jpg',
      Category: 'Fruits',
      Parentcategory: 'Fruits',
      CategoryCode: 'CT003',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product4.jpg',
      Category: 'Fruits',
      Parentcategory: 'Fruits',
      CategoryCode: 'CT004',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product5.jpg',
      Category: 'Accessories',
      Parentcategory: 'Accessories',
      CategoryCode: 'CT005',
      isSelected: false,
      Description: 'Accessories Description	',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product6.jpg',
      Category: 'Shoes',
      Parentcategory: 'Shoes',
      CategoryCode: 'CT006',
      isSelected: false,
      Description: 'Shoes Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product7.jpg',
      Category: 'Fruits',
      Parentcategory: 'Fruits',
      CategoryCode: 'CT007',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product8.jpg',
      Category: 'Fruits',
      Parentcategory: 'Fruits',
      CategoryCode: 'CT008',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product9.jpg',
      Category: 'Computers',
      Parentcategory: 'Computers',
      CategoryCode: 'CT009',
      isSelected: false,
      Description: 'Computers Description	',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product10.jpg',
      Category: 'Health Care',
      Parentcategory: 'Health Care',
      CategoryCode: 'CT0010',
      isSelected: false,
      Description: 'Health Care Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product4.jpg',
      Category: 'Fruits',
      Parentcategory: 'Fruits',
      CategoryCode: 'CT004',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product5.jpg',
      Category: 'Accessories',
      Parentcategory: 'Accessories',
      CategoryCode: 'CT005',
      isSelected: false,
      Description: 'Accessories Description	',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product6.jpg',
      Category: 'Shoes',
      Parentcategory: 'Shoes',
      CategoryCode: 'CT006',
      isSelected: false,
      Description: 'Shoes Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product7.jpg',
      Category: 'Fruits',
      Parentcategory: 'Fruits',
      CategoryCode: 'CT007',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product8.jpg',
      Category: 'Fruits',
      Parentcategory: 'Fruits',
      CategoryCode: 'CT008',
      isSelected: false,
      Description: 'Fruits Description',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product9.jpg',
      Category: 'Computers',
      Parentcategory: 'Computers',
      CategoryCode: 'CT009',
      isSelected: false,
      Description: 'Computers Description	',
      CreatedBy: 'Admin',
    },
    {
      Image: 'assets/img/product/product10.jpg',
      Category: 'Health Care',
      Parentcategory: 'Health Care',
      CategoryCode: 'CT0010',
      isSelected: false,
      Description: 'Health Care Description',
      CreatedBy: 'Admin',
    },
  ];
  public brandList = [
    {
      Image: 'assets/img/brand/adidas.png',
      BrandName: 'Adidas',
      BrandDescription: 'Shoes, sportswear',
      isSelected: false,
    },
    {
      Image: 'assets/img/brand/colgate.png',
      BrandName: 'Colgate',
      BrandDescription: 'Oral hygiene. Toothbrushes',
      isSelected: false,
    },
    {
      Image: 'assets/img/brand/samsung.png',
      BrandName: 'samsung',
      BrandDescription: 'Electronics',
      isSelected: false,
    },
  ];
  public salesList = [
    {
      CustomerName: 'Sheila James',
      Date: '19 Match 2023',
      isSelected: false,
      Reference: 'SL0101',
      Status: 'Completed',
      Payment: 'Paid',
      Total: '100.00',
      Paid: '100.00',
      Due: '0.00',
      Biller: 'Admin',
    },
    {
      CustomerName: 'John Alex',
      Date: '19 March 2023	',
      isSelected: false,
      Reference: 'SL0102',
      Status: 'Completed',
      Payment: 'Paid',
      Total: '100.00',
      Paid: '100.00',
      Due: '0.00',
      Biller: 'Admin',
    }
  ];
  public salesreturnLists = [
    {
      ProductName: 'Macbook pro',
      Date: '19 Nov 2022',
      Customer: 'Thomas',
      Status: 'Received',
      GrandTotal: '550',
      isSelected: false,
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product1.jpg',
    },
    {
      ProductName: 'Orange',
      Date: '19 Nov 2022',
      Customer: 'Benjamin',
      Status: 'Pending',
      GrandTotal: '550',
      isSelected: false,
      Paid: '120',
      Due: '550',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product2.jpg',
    },
    {
      ProductName: 'Pineapple',
      Date: '19 Nov 2022',
      Customer: 'James',
      Status: 'Pending',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product3.jpg',
    },
    {
      ProductName: 'Strawberry',
      Date: '19 Nov 2022',
      Customer: 'Bruklin',
      Status: 'Received',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product4.jpg',
    },
    {
      ProductName: 'Avocat',
      Date: '19 Nov 2022',
      Customer: 'Beverly',
      Status: 'Pending',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product5.jpg',
    },
    {
      ProductName: 'Macbook Pro',
      Date: '19 Nov 2022',
      Customer: 'Best Power Tools	',
      Status: 'Received',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Apple Earpods',
      Date: '19 Nov 2022',
      Customer: 'Apex Computers',
      Status: 'Ordered',
      GrandTotal: '1000',
      isSelected: false,
      Paid: '500',
      Due: '1000',
      PaymentStatus: 'Partial',
      img: 'assets/img/product/product7.jpg',
    },
    {
      ProductName: 'Macbook pro',
      Date: '19 Nov 2022',
      Customer: 'Thomas',
      Status: 'Received',
      GrandTotal: '550',
      isSelected: false,
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product1.jpg',
    },
    {
      ProductName: 'Orange',
      Date: '19 Nov 2022',
      Customer: 'Benjamin',
      Status: 'Pending',
      GrandTotal: '550',
      isSelected: false,
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Partial',
      img: 'assets/img/product/product2.jpg',
    },
    {
      ProductName: 'Pineapple',
      Date: '19 Nov 2022',
      Customer: 'James',
      Status: 'Pending',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product3.jpg',
    },
    {
      ProductName: 'Strawberry',
      Date: '19 Nov 2022',
      Customer: 'Bruklin',
      Status: 'Received',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product4.jpg',
    },
    {
      ProductName: 'Avocat',
      Date: '19 Nov 2022',
      Customer: 'Beverly',
      Status: 'Pending',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product5.jpg',
    },
    {
      ProductName: 'Macbook Pro',
      Date: '19 Nov 2022',
      Customer: 'Best Power Tools	',
      Status: 'Received',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Apple Earpods',
      Date: '19 Nov 2022',
      Customer: 'Apex Computers',
      Status: 'Ordered',
      GrandTotal: '1000',
      isSelected: false,
      Paid: '500',
      Due: '1000',
      PaymentStatus: 'Partial',
      img: 'assets/img/product/product7.jpg',
    },
  ];
  public purchaseList = [
    {
      SupplierName: 'Apex Computers',
      Reference: 'PT001',
      Date: '19 Nov 2022	',
      Status: 'Received',
      GrandTotal: '550',
      isSelected: false,
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Paid',
    },
    {
      SupplierName: 'Modern Automobile',
      Reference: 'PT002',
      Date: '19 Nov 2022	',
      Status: 'Received',
      GrandTotal: '410',
      isSelected: false,
      Paid: '410',
      Due: '410',
      PaymentStatus: 'Paid',
    },
    {
      SupplierName: 'AIM Infotech	',
      Reference: 'PT003',
      Date: '19 Nov 2022	',
      Status: 'Pending',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
    },
    {
      SupplierName: 'Best Power Tools	',
      Reference: 'PT004',
      Date: '19 Nov 2022	',
      Status: 'Received',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
    },
    {
      SupplierName: 'Best Power Tools	',
      Reference: 'PT005',
      Date: '19 Nov 2022	',
      Status: 'Pending',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
    },
    {
      SupplierName: 'Best Power Tools	',
      Reference: 'PT006',
      Date: '19 Nov 2022	',
      Status: 'Received',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
    },
    {
      SupplierName: 'Apex Computers',
      Reference: 'PT007',
      Date: '19 Nov 2022	',
      Status: 'Ordered',
      GrandTotal: '1000',
      isSelected: false,
      Paid: '500',
      Due: '1000',
      PaymentStatus: 'Partial',
    },
    {
      SupplierName: 'Apex Computers',
      Reference: 'PT008',
      Date: '19 Nov 2022	',
      Status: 'Received',
      GrandTotal: '550',
      isSelected: false,
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Paid',
    },
    {
      SupplierName: 'Modern Automobile	',
      Reference: 'PT009',
      Date: '19 Nov 2022	',
      Status: 'Received',
      GrandTotal: '410',
      isSelected: false,
      Paid: '410',
      Due: '410',
      PaymentStatus: 'Paid',
    },
    {
      SupplierName: 'AIM Infotech	',
      Reference: 'PT010',
      Date: '19 Nov 2022	',
      Status: 'Pending',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
    },
    {
      SupplierName: 'Best Power Tools	',
      Reference: 'PT011',
      Date: '19 Nov 2022	',
      Status: 'Received',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
    },
    {
      SupplierName: 'Best Power Tools	',
      Reference: 'PT012',
      Date: '19 Nov 2022	',
      Status: 'Pending',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
    },
    {
      SupplierName: 'Best Power Tools	',
      Reference: 'PT013',
      Date: '19 Nov 2022	',
      Status: 'Received',
      GrandTotal: '210',
      isSelected: false,
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
    },
    {
      SupplierName: 'Apex Computers	',
      Reference: 'PT014',
      Date: '19 Nov 2022	',
      Status: 'Ordered',
      GrandTotal: '1000',
      isSelected: false,
      Paid: '500',
      Due: '1000',
      PaymentStatus: 'Partial',
    },
  ];
  public salesreturnList = [
    {
      ProductName: 'Macbook pro',
      Date: '19 Nov 2022',
      Customer: 'Thomas',
      isSelected: false,
      Status: 'Received',
      GrandTotal: '550',
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product1.jpg',
    },
    {
      ProductName: 'Orange',
      Date: '19 Nov 2022',
      Customer: 'Benjamin',
      isSelected: false,
      Status: 'Pending',
      GrandTotal: '550',
      Paid: '120',
      Due: '550',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product2.jpg',
    },
    {
      ProductName: 'Pineapple',
      Date: '19 Nov 2022',
      Customer: 'James',
      isSelected: false,
      Status: 'Pending',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product3.jpg',
    },
    {
      ProductName: 'Strawberry',
      Date: '19 Nov 2022',
      Customer: 'Bruklin',
      isSelected: false,
      Status: 'Received',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product4.jpg',
    },
    {
      ProductName: 'Avocat',
      Date: '19 Nov 2022',
      Customer: 'Beverly',
      isSelected: false,
      Status: 'Pending',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product5.jpg',
    },
    {
      ProductName: 'Macbook Pro',
      Date: '19 Nov 2022',
      Customer: 'Best Power Tools	',
      isSelected: false,
      Status: 'Received',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Apple Earpods',
      Date: '19 Nov 2022',
      Customer: 'Apex Computers',
      isSelected: false,
      Status: 'Ordered',
      GrandTotal: '1000',
      Paid: '500',
      Due: '1000',
      PaymentStatus: 'Partial',
      img: 'assets/img/product/product7.jpg',
    },
    {
      ProductName: 'Macbook pro',
      Date: '19 Nov 2022',
      Customer: 'Thomas',
      isSelected: false,
      Status: 'Received',
      GrandTotal: '550',
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product1.jpg',
    },
    {
      ProductName: 'Orange',
      Date: '19 Nov 2022',
      Customer: 'Benjamin',
      isSelected: false,
      Status: 'Pending',
      GrandTotal: '550',
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Partial',
      img: 'assets/img/product/product2.jpg',
    },
    {
      ProductName: 'Pineapple',
      Date: '19 Nov 2022',
      Customer: 'James',
      isSelected: false,
      Status: 'Pending',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product3.jpg',
    },
    {
      ProductName: 'Strawberry',
      Date: '19 Nov 2022',
      Customer: 'Bruklin',
      isSelected: false,
      Status: 'Received',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product4.jpg',
    },
    {
      ProductName: 'Avocat',
      Date: '19 Nov 2022',
      Customer: 'Beverly',
      isSelected: false,
      Status: 'Pending',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
      img: 'assets/img/product/product5.jpg',
    },
    {
      ProductName: 'Macbook Pro',
      Date: '19 Nov 2022',
      Customer: 'Best Power Tools	',
      isSelected: false,
      Status: 'Received',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Apple Earpods',
      Date: '19 Nov 2022',
      Customer: 'Apex Computers',
      isSelected: false,
      Status: 'Ordered',
      GrandTotal: '1000',
      Paid: '500',
      Due: '1000',
      PaymentStatus: 'Partial',
      img: 'assets/img/product/product7.jpg',
    },
  ];
  public purchaseReturnList = [
    {
      Image: 'assets/img/product/product1.jpg',
      Date: '2/27/2022',
      Supplier: 'Apex Computers',
      isSelected: false,
      Reference: 'PT001',
      Status: 'Received',
      GrandTotal: '550',
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Paid',
    },
    {
      Image: 'assets/img/product/product2.jpg',
      Date: '1/15/2022',
      Supplier: 'Modern Automobile',
      isSelected: false,
      Reference: 'PT002',
      Status: 'Ordered',
      GrandTotal: '550',
      Paid: '120',
      Due: '550',
      PaymentStatus: 'Partial',
    },
    {
      Image: 'assets/img/product/product3.jpg',
      Date: '3/24/2022',
      Supplier: 'AIM Infotech	',
      isSelected: false,
      Reference: 'PT003',
      Status: 'Pending',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
    },
    {
      Image: 'assets/img/product/product4.jpg',
      Date: '1/15/2022',
      Supplier: 'Best Power Tools',
      isSelected: false,
      Reference: 'PT004',
      Status: 'Received',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
    },
    {
      Image: 'assets/img/product/product5.jpg',
      Date: '1/15/2022',
      Supplier: 'AIM Infotech	',
      isSelected: false,
      Reference: 'PT005',
      Status: 'Pending',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'UnPaid',
    },
    {
      Image: 'assets/img/product/product6.jpg',
      Date: '3/24/2022',
      Supplier: 'Best Power Tools',
      isSelected: false,
      Reference: 'PT006',
      Status: 'Received',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
    },
    {
      Image: 'assets/img/product/product7.jpg',
      Date: '1/15/2022',
      Supplier: 'Apex Computers',
      isSelected: false,
      Reference: 'PT007',
      Status: 'Ordered',
      GrandTotal: '1000',
      Paid: '500',
      Due: '1000',
      PaymentStatus: 'Partial',
    },
    {
      Image: 'assets/img/product/product8.jpg',
      Date: '3/24/2022',
      Supplier: 'Best Power Tools',
      isSelected: false,
      Reference: 'PT008',
      Status: 'Received',
      GrandTotal: '210',
      Paid: '120',
      Due: '210',
      PaymentStatus: 'Paid',
    },
    {
      Image: 'assets/img/product/product9.jpg',
      Date: '3/24/2022',
      Supplier: 'Hatimi Hardware & Tools',
      isSelected: false,
      Reference: 'PT009',
      Status: 'Pending',
      GrandTotal: '5500',
      Paid: '550',
      Due: '5500',
      PaymentStatus: 'UnPaid',
    },
    {
      Image: 'assets/img/product/product10.jpg',
      Date: '3/24/2022',
      Supplier: 'Best Power Tools',
      isSelected: false,
      Reference: 'PT0010',
      Status: 'Pending',
      GrandTotal: '2580',
      Paid: '1250',
      Due: '2580',
      PaymentStatus: 'UnPaid',
    },
    {
      Image: 'assets/img/product/product5.jpg',
      Date: '3/24/2022',
      Supplier: 'Best Power Tools',
      isSelected: false,
      Reference: 'PT0011',
      Status: 'Pending',
      GrandTotal: '2580',
      Paid: '1250',
      Due: '2580',
      PaymentStatus: 'UnPaid',
    },
  ];
  public supplierList = [
    {
      img: 'assets/img/product/product6.jpg',
      SupplierName: 'Apex Computers',
      code: '201',
      isSelected: false,
      Customer: '+12163547758',
      email: 'thomas@example.com',
      Country: 'China',
    },
    {
      img: 'assets/img/product/product8.jpg',
      SupplierName: 'Modern Automobile',
      code: '202',
      isSelected: false,
      Customer: '123-456-888',
      email: 'customer@example.com',
      Country: 'USA',
    },
    {
      img: 'assets/img/product/product7.jpg',
      SupplierName: 'AIM Infotech',
      code: '521',
      isSelected: false,
      Customer: '123-456-888',
      email: 'customer@example.com',
      Country: 'USA',
    },
    {
      img: 'assets/img/product/product1.jpg',
      SupplierName: 'Best Power Tools',
      code: '555',
      isSelected: false,
      Customer: '123-456-888',
      email: 'bruklin@example.com',
      Country: 'Thailand',
    },
    {
      img: 'assets/img/product/product7.jpg',
      SupplierName: 'AIM Infotech',
      code: '325',
      isSelected: false,
      Customer: '+12163547758',
      email: 'Beverly@example.com',
      Country: 'Phuket island',
    },
    {
      img: 'assets/img/product/product1.jpg',
      SupplierName: 'Best Power Tools',
      code: '589',
      isSelected: false,
      Customer: '123-456-888',
      email: 'Huber@example.com',
      Country: 'Germany',
    },
    {
      img: 'assets/img/product/product6.jpg',
      SupplierName: 'Apex Computers',
      code: '254',
      isSelected: false,
      Customer: '+12163547758',
      email: 'customer@example.com',
      Country: 'Angola',
    },
    {
      img: 'assets/img/product/product7.jpg',
      SupplierName: 'Vinayak Tools',
      code: '681',
      isSelected: false,
      Customer: '123-456-888',
      email: 'john@example.com',
      Country: 'Albania',
    },
    {
      img: 'assets/img/product/product1.jpg',
      SupplierName: 'Best Power Tools',
      code: '555',
      isSelected: false,
      Customer: '123-456-888',
      email: 'bruklin@example.com',
      Country: 'Thailand',
    },
    {
      img: 'assets/img/product/product7.jpg',
      SupplierName: 'AIM Infotech',
      code: '325',
      isSelected: false,
      Customer: '+12163547758	',
      email: 'Beverly@example.com	',
      Country: 'Phuket island',
    },
    {
      img: 'assets/img/product/product1.jpg',
      SupplierName: 'Best Power Tools',
      code: '589',
      isSelected: false,
      Customer: '123-456-888',
      email: 'Huber@example.com',
      Country: 'Germany',
    },
    {
      img: 'assets/img/product/product6.jpg',
      SupplierName: 'Apex Computers',
      code: '254',
      isSelected: false,
      Customer: '+12163547758',
      email: 'customer@example.com',
      Country: 'Angola',
    },
    {
      img: 'assets/img/product/product1.jpg',
      SupplierName: 'Vinayak Tools',
      code: '681',
      isSelected: false,
      Customer: '123-456-888',
      email: 'john@example.com',
      Country: 'Albania',
    },
  ];
  public peopleUserList = [
    {
      img: 'assets/img/customer/customer1.jpg',
      Firstname: 'Thomas',
      Lastname: 'Thomas',
      Username: 'Thomas',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: false,
      email: 'thomas@example.com',
    },
    {
      img: 'assets/img/customer/customer2.jpg',
      Firstname: 'Benjamin',
      Lastname: 'Franklin',
      Username: '504Benjamin',
      Phone: '123-456-888',
      isSelected: false,
      isStatus: false,
      email: 'customer@example.com',
    },
    {
      img: 'assets/img/customer/customer3.jpg',
      Firstname: 'James',
      Lastname: 'James',
      Username: 'James 524',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: true,
      email: 'james@example.com',
    },
    {
      img: 'assets/img/customer/customer4.jpg',
      Firstname: 'Bruklin',
      Lastname: 'Bruklin',
      Username: ' Bruklin2022',
      Phone: '123-456-888	',
      isSelected: false,
      isStatus: true,
      email: 'bruklin@example.com',
    },
    {
      img: 'assets/img/customer/customer5.jpg',
      Firstname: 'Franklin',
      Lastname: 'Jacob',
      Username: ' BeverlyWIN25',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: true,
      email: 'Beverly@example.com',
    },
    {
      img: 'assets/img/customer/customer6.jpg',
      Firstname: 'B. Huber',
      Lastname: 'Jacob',
      Username: ' BeverlyWIN25',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: false,
      email: 'Huber@example.com',
    },
    {
      img: 'assets/img/customer/customer7.jpg',
      Firstname: 'Alwin',
      Lastname: 'Alwin',
      Username: ' Alwin243',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: false,
      email: 'customer@example.com	',
    },
    {
      img: 'assets/img/customer/customer8.jpg',
      Firstname: 'Fred john	',
      Lastname: 'john',
      Username: ' FredJ25',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: true,
      email: 'john@example.com',
    },
    {
      img: 'assets/img/customer/customer1.jpg',
      Firstname: 'Rasmussen',
      Lastname: 'Gothic',
      Username: ' Cras56',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: true,
      email: 'Rasmussen@example.com',
    },
    {
      img: 'assets/img/customer/customer2.jpg',
      Firstname: 'Grace',
      Lastname: 'Halena',
      Username: ' Grace2022',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: true,
      email: 'customer@example.com',
    },
    {
      img: 'assets/img/customer/customer3.jpg',
      Firstname: 'Rasmussen',
      Lastname: 'Gothic',
      Username: ' Cras56',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: true,
      email: 'Rasmussen@example.com',
    },
    {
      img: 'assets/img/customer/customer4.jpg',
      Firstname: 'Grace',
      Lastname: 'Halena',
      Username: ' Grace2022',
      Phone: '+12163547758',
      isSelected: false,
      isStatus: false,
      email: 'customer@example.com',
    },
  ];
  public storeList = [
    {
      Storename: 'Thomas',
      Username: 'Thomas21',
      Phone: '+12163547758',
      isSelected: false,
      email: 'thomas@example.com',
      isStatus: true,
    },
    {
      Storename: 'Benjamin',
      Username: '504Benjamin',
      Phone: '123-456-888',
      isSelected: false,
     isStatus: false,
      email: 'customer@example.com',
    },
    {
      Storename: 'James',
      Username: 'James 524',
      Phone: '+12163547758',
      isSelected: false,
     isStatus: false,
      email: 'james@example.com',
    },
    {
      Storename: 'Bruklin',
      Username: ' Bruklin2022',
      Phone: '123-456-888	',
      isSelected: false,
     isStatus: false,
      email: 'bruklin@example.com',
    },
    {
      Storename: 'Franklin',
      Username: ' BeverlyWIN25',
      Phone: '+12163547758',
      isSelected: false,
     isStatus: false,
      email: 'Beverly@example.com',
    },
    {
      Storename: 'B. Huber',
      Username: ' BeverlyWIN25',
      Phone: '+12163547758',
      isSelected: false,
     isStatus: true,
      email: 'Huber@example.com',
    },
    {
      Storename: 'Alwin',
      Username: ' Alwin243',
      Phone: '+12163547758	',
      isSelected: false,
     isStatus: true,
      email: 'customer@example.com	',
    },
    {
      Storename: 'Fred john	',
      Username: ' FredJ25',
      Phone: '+12163547758',
      isSelected: false,
     isStatus: false,
      email: 'john@example.com',
    },
    {
      Storename: 'Rasmussen',
      Username: ' Cras56',
      Phone: '+12163547758	',
      isSelected: false,
     isStatus: false,
      email: 'Rasmussen@example.com',
    },
    {
      Storename: 'Grace',
      Username: ' Grace2022',
      Phone: '+12163547758',
      isSelected: false,
     isStatus: false,
      email: 'customer@example.com',
    },
    {
      Storename: 'Rasmussen',
      Username: ' Cras56',
      Phone: '+12163547758	',
      isSelected: false,
     isStatus: true,
      email: 'Rasmussen@example.com',
    },
    {
      Storename: 'Grace',
      Username: ' Grace2022',
      Phone: '+12163547758',
      isSelected: false,
     isStatus: true,
      email: 'customer@example.com',
    },
  ];
  public stateList = [
    {
      StateName: 'Beijing',
      CountryName: 'China',
      isSelected: false,
      isStatus:true
    },
    {
      StateName: 'Newyork',
      CountryName: 'USA',
      isSelected: false,
      isStatus:false
    },
    {
      StateName: 'Athens',
      CountryName: 'Greece',
      isSelected: false,
      isStatus:true
    },
    {
      StateName: 'Thailand',
      CountryName: 'Bangkok',
      isSelected: false,
      isStatus:false
    },
    {
      StateName: 'Phuket island	',
      CountryName: 'Mueang Phuket',
      isSelected: false,
      isStatus:true
    },
    {
      StateName: 'Germany',
      CountryName: 'Berlin',
      isSelected: false,
      isStatus:false
    },
    {
      StateName: 'Angola',
      CountryName: 'Luanda',
      isSelected: false,
      isStatus:true
    },
    {
      StateName: 'Albania',
      CountryName: 'Albania',
      isSelected: false,
      isStatus:false
    },
    {
      StateName: 'Turkey',
      CountryName: 'Ankara',
      isSelected: false,
      isStatus:false
    },
    {
      StateName: 'Phuket island',
      CountryName: 'Mueang Phuket',
      isSelected: false,
      isStatus:false
    },
    {
      StateName: 'Germany',
      CountryName: 'Berlin',
      isSelected: false,
      isStatus:false
    },
    {
      StateName: 'Angola',
      CountryName: 'Luanda',
      isSelected: false,
      isStatus:false
    },
    {
      StateName: 'Albania',
      CountryName: 'Albania',
      isSelected: false,
      isStatus:false
    },
    {
      StateName: 'Turkey',
      CountryName: 'Ankara',
      isSelected: false,
      isStatus:false
    },
  ];
  public purchaseOrderReport = [
    {
      img: 'assets/img/product/product1.jpg',
      ProductName: 'Macbook pro',
      isSelected: false,
      Purchasedamount: '38698.00',
      PurchasedQTY: '1248',
      InstockQTY: '1356',
    },
    {
      img: 'assets/img/product/product2.jpg',
      ProductName: 'Orange',
      isSelected: false,
      Purchasedamount: '36080.00',
      PurchasedQTY: '110',
      InstockQTY: '131',
    },
    {
      img: 'assets/img/product/product3.jpg',
      ProductName: 'Pineapple',
      isSelected: false,
      Purchasedamount: '21000.00',
      PurchasedQTY: '106',
      InstockQTY: '131',
    },
    {
      img: 'assets/img/product/product4.jpg',
      ProductName: 'Strawberry',
      isSelected: false,
      Purchasedamount: '11000.00',
      PurchasedQTY: '105',
      InstockQTY: '100',
    },
    {
      img: 'assets/img/product/product5.jpg',
      ProductName: 'Sunglasses',
      isSelected: false,
      Purchasedamount: '10600.00',
      PurchasedQTY: '105',
      InstockQTY: '100',
    },
    {
      img: 'assets/img/product/product6.jpg',
      ProductName: 'OrangeUnpaired gray',
      isSelected: false,
      Purchasedamount: '9984.00',
      PurchasedQTY: '50',
      InstockQTY: '50',
    },
    {
      img: 'assets/img/product/product7.jpg',
      ProductName: 'Avocat',
      isSelected: false,
      Purchasedamount: '4500.00',
      PurchasedQTY: '41',
      InstockQTY: '29',
    },
    {
      img: 'assets/img/product/product8.jpg',
      ProductName: 'Banana',
      isSelected: false,
      Purchasedamount: '900.00',
      PurchasedQTY: '28',
      InstockQTY: '24',
    },
    {
      img: 'assets/img/product/product9.jpg',
      ProductName: 'Earphones',
      isSelected: false,
      Purchasedamount: '500.00',
      PurchasedQTY: '20',
      InstockQTY: '11',
    },
    {
      img: 'assets/img/product/product8.jpg',
      ProductName: 'Banana',
      isSelected: false,
      Purchasedamount: '900.00',
      PurchasedQTY: '28',
      InstockQTY: '24',
    },
    {
      img: 'assets/img/product/product9.jpg',
      ProductName: 'Earphones',
      isSelected: false,
      Purchasedamount: '500.00',
      PurchasedQTY: '20',
      InstockQTY: '11',
    },
  ];
  public inventoryReport = [
    {
      ProductName: 'Macbook pro',
      SKU: 'PT001',
      Category: 'Computers',
      isSelected: false,
      Brand: 'N/D',
      price: '1500.00',
      Unit: 'pc',
      Instockqty: '1356',
      img: 'assets/img/product/product1.jpg',
    },
    {
      ProductName: 'Orange',
      SKU: 'PT002',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'kg',
      Instockqty: '131',
      img: 'assets/img/product/product2.jpg',
    },
    {
      ProductName: 'Pineapple',
      SKU: 'PT003',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'kg',
      Instockqty: '72',
      img: 'assets/img/product/product3.jpg',
    },
    {
      ProductName: 'Strawberry',
      SKU: 'PT004',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'kg',
      Instockqty: '100',
      img: 'assets/img/product/product4.jpg',
    },
    {
      ProductName: 'Sunglasses',
      SKU: 'PT005',
      Category: 'Accessories',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'pc',
      Instockqty: '100',
      img: 'assets/img/product/product5.jpg',
    },
    {
      ProductName: 'Unpaired gray',
      SKU: 'PT006',
      Category: '	Shoes',
      isSelected: false,
      Brand: 'Adidas',
      price: '100.00',
      Unit: 'pc',
      Instockqty: '50',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Avocat',
      SKU: 'PT007',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '5.00',
      Unit: 'kg',
      Instockqty: '29',
      img: 'assets/img/product/product7.jpg',
    },
    {
      ProductName: 'Banana',
      SKU: 'PT008',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'kg',
      Instockqty: '24',
      img: 'assets/img/product/product8.jpg',
    },
    {
      ProductName: 'Earphones',
      SKU: 'PT009',
      Category: 'Computers',
      isSelected: false,
      Brand: 'N/D',
      price: '15.00',
      Unit: 'pc',
      Instockqty: '11',
      img: 'assets/img/product/product9.jpg',
    },
    {
      ProductName: 'Banana',
      SKU: 'PT010',
      Category: 'Health Care ',
      isSelected: false,
      Brand: 'N/D',
      price: '5.00',
      Unit: 'kg',
      Instockqty: '16',
      img: 'assets/img/product/product8.jpg',
    },
    {
      ProductName: 'Unpaired gray',
      SKU: 'PT006',
      Category: '	Shoes',
      isSelected: false,
      Brand: 'Adidas',
      price: '100.00',
      Unit: 'pc',
      Instockqty: '50',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Avocat',
      SKU: 'PT007',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '5.00',
      Unit: 'kg',
      Instockqty: '29',
      img: 'assets/img/product/product7.jpg',
    },
    {
      ProductName: 'Banana',
      SKU: 'PT008',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      price: '10.00',
      Unit: 'kg',
      Instockqty: '24',
      img: 'assets/img/product/product8.jpg',
    },
    {
      ProductName: 'Earphones',
      SKU: 'PT009',
      Category: 'Computers',
      isSelected: false,
      Brand: 'N/D',
      price: '15.00',
      Unit: 'pc',
      Instockqty: '11',
      img: 'assets/img/product/product9.jpg',
    },
    {
      ProductName: 'Banana',
      SKU: 'PT010',
      Category: 'Health Care',
      isSelected: false,
      Brand: 'N/D',
      price: '5.00',
      Unit: 'kg',
      Instockqty: '16',
      img: 'assets/img/product/product8.jpg',
    },
  ];
  public salesReport = [
    {
      ProductName: 'Macbook pro',
      SKU: 'PT001',
      Category: 'Computers',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '1500.00',
      Soldqty: '1',
      Instockqty: '1356',
      img: 'assets/img/product/product1.jpg',
    },
    {
      ProductName: 'Orange',
      SKU: 'PT002',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '10.00',
      Soldqty: '1',
      Instockqty: '131',
      img: 'assets/img/product/product2.jpg',
    },
    {
      ProductName: 'Pineapple',
      SKU: 'PT003',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '10.00',
      Soldqty: '3',
      Instockqty: '72',
      img: 'assets/img/product/product3.jpg',
    },
    {
      ProductName: 'Strawberry',
      SKU: 'PT004',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '10.00',
      Soldqty: '1',
      Instockqty: '100',
      img: 'assets/img/product/product4.jpg',
    },
    {
      ProductName: 'Sunglasses',
      SKU: 'PT005',
      Category: 'Accessories',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '10.00',
      Soldqty: '1',
      Instockqty: '100',
      img: 'assets/img/product/product5.jpg',
    },
    {
      ProductName: 'Unpaired gray',
      SKU: 'PT006',
      Category: '	Shoes',
      isSelected: false,
      Brand: 'Adidas',
      Soldamount: '100.00',
      Soldqty: '3',
      Instockqty: '50',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Avocat',
      SKU: 'PT007',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '5.00',
      Soldqty: '5',
      Instockqty: '29',
      img: 'assets/img/product/product7.jpg',
    },
    {
      ProductName: 'Banana',
      SKU: 'PT008',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '10.00',
      Soldqty: '1',
      Instockqty: '24',
      img: 'assets/img/product/product8.jpg',
    },
    {
      ProductName: 'Earphones',
      SKU: 'PT009',
      Category: 'Computers',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '15.00',
      Soldqty: '2',
      Instockqty: '11',
      img: 'assets/img/product/product9.jpg',
    },
    {
      ProductName: 'Banana',
      SKU: 'PT010',
      Category: 'Health Care',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '5.00',
      Soldqty: '5',
      Instockqty: '16',
      img: 'assets/img/product/product8.jpg',
    },
    {
      ProductName: 'Unpaired gray',
      SKU: 'PT006',
      Category: '	Shoes',
      isSelected: false,
      Brand: 'Adidas',
      Soldamount: '100.00',
      Soldqty: '3',
      Instockqty: '50',
      img: 'assets/img/product/product6.jpg',
    },
    {
      ProductName: 'Avocat',
      SKU: 'PT007',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '5.00',
      Soldqty: '5',
      Instockqty: '29',
      img: 'assets/img/product/product7.jpg',
    },
    {
      ProductName: 'Banana',
      SKU: 'PT008',
      Category: 'Fruits',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '10.00',
      Soldqty: '1',
      Instockqty: '24',
      img: 'assets/img/product/product8.jpg',
    },
    {
      ProductName: 'Earphones',
      SKU: 'PT009',
      Category: 'Computers',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '15.00',
      Soldqty: '2',
      Instockqty: '11',
      img: 'assets/img/product/product9.jpg',
    },
    {
      ProductName: 'Banana',
      SKU: 'PT010',
      Category: 'Health Care',
      isSelected: false,
      Brand: 'N/D',
      Soldamount: '5.00',
      Soldqty: '5',
      Instockqty: '16',
      img: 'assets/img/product/product8.jpg',
    },
  ];
  public purchaseReport = [
    {
      img: 'assets/img/product/product1.jpg',
      ProductName: 'Macbook pro',
      isSelected: false,
      Purchasedamount: '38698.00',
      PurchasedQTY: '1248',
      InstockQTY: '1356',
    },
    {
      img: 'assets/img/product/product2.jpg',
      ProductName: 'Orange',
      isSelected: false,
      Purchasedamount: '36080.00',
      PurchasedQTY: '110',
      InstockQTY: '131',
    },
    {
      img: 'assets/img/product/product3.jpg',
      ProductName: 'Pineapple',
      isSelected: false,
      Purchasedamount: '21000.00',
      PurchasedQTY: '106',
      InstockQTY: '131',
    },
    {
      img: 'assets/img/product/product4.jpg',
      ProductName: 'Strawberry',
      isSelected: false,
      Purchasedamount: '11000.00',
      PurchasedQTY: '105',
      InstockQTY: '100',
    },
    {
      img: 'assets/img/product/product5.jpg',
      ProductName: 'Sunglasses',
      isSelected: false,
      Purchasedamount: '10600.00',
      PurchasedQTY: '105',
      InstockQTY: '100',
    },
    {
      img: 'assets/img/product/product6.jpg',
      ProductName: 'Unpaired gray',
      isSelected: false,
      Purchasedamount: '9984.00',
      PurchasedQTY: '50',
      InstockQTY: '50',
    },
    {
      img: 'assets/img/product/product7.jpg',
      ProductName: 'Avocat',
      isSelected: false,
      Purchasedamount: '4500.00',
      PurchasedQTY: '41',
      InstockQTY: '29',
    },
    {
      img: 'assets/img/product/product8.jpg',
      ProductName: 'Banana',
      isSelected: false,
      Purchasedamount: '900.00',
      PurchasedQTY: '28',
      InstockQTY: '24',
    },
    {
      img: 'assets/img/product/product9.jpg',
      ProductName: 'Earphones',
      isSelected: false,
      Purchasedamount: '500.00',
      PurchasedQTY: '20',
      InstockQTY: '11',
    },
    {
      img: 'assets/img/product/product8.jpg',
      ProductName: 'Banana',
      isSelected: false,
      Purchasedamount: '900.00',
      PurchasedQTY: '28',
      InstockQTY: '24',
    },
    {
      img: 'assets/img/product/product9.jpg',
      ProductName: 'Earphones',
      isSelected: false,
      Purchasedamount: '500.00',
      PurchasedQTY: '20',
      InstockQTY: '11',
    },
  ];
  public customerReport = [
    {
      Customercode: 'CT_1001',
      Customername: 'Thomas21',
      isSelected: false,
      Amount: '1500.00',
      Paid: '1500.00',
      Amountdue: '1500.00',
      Status: 'Completed',
      PaymentStatus: 'Paid',
    },
    {
      Customercode: 'CT_1002',
      Customername: '504Benjamin',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'Overdue',
    },
    {
      Customercode: 'CT_1003',
      Customername: 'James 524',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'Overdue',
    },
    {
      Customercode: 'CT_1004',
      Customername: 'Bruklin2022',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'Paid',
    },
    {
      Customercode: 'CT_1005',
      Customername: 'BeverlyWIN25',
      isSelected: false,
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Completed',
      PaymentStatus: 'Overdue',
    },
    {
      Customercode: 'CT_1006',
      Customername: 'BHR256',
      isSelected: false,
      Amount: '100.00',
      Paid: '100.00',
      Amountdue: '100.00',
      Status: 'Completed',
      PaymentStatus: 'Overdue',
    },
    {
      Customercode: 'CT_1007',
      Customername: 'Alwin243',
      isSelected: false,
      Amount: '5.00',
      Paid: '5.00',
      Amountdue: '5.00',
      Status: 'Completed',
      PaymentStatus: 'Paid',
    },
    {
      Customercode: 'CT_1008',
      Customername: 'FredJ25',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'UnPaid',
    },
    {
      Customercode: 'CT_1009',
      Customername: 'FredJ25',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'UnPaid',
    },
    {
      Customercode: 'CT_1010',
      Customername: 'Cras56',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      Amountdue: '15.00',
      Status: 'Completed',
      PaymentStatus: 'UnPaid',
    },
    {
      Customercode: 'CT_1011',
      Customername: 'Grace2022',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      Amountdue: '15.00',
      Status: 'Completed',
      PaymentStatus: 'UnPaid',
    },
    {
      Customercode: 'CT_1011',
      Customername: 'Cras56	',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      Amountdue: '15.00',
      Status: 'Completed',
      PaymentStatus: 'UnPaid',
    },
    {
      Customercode: 'CT_1012',
      Customername: 'Grace2022',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      Amountdue: '15.00',
      Status: 'Completed',
      PaymentStatus: 'UnPaid',
    },
  ];
  public paymentSettings = [
    {
      PaymentTypeName: 'Cash',
      isSelected: false,
      isStatus: true,
    },
    {
      PaymentTypeName: 'Card',
      isSelected: false,
      isStatus: false,
    },
    {
      PaymentTypeName: 'Credit',
      isSelected: false,
      isStatus: true,
    },
  ];
  public currencySettings = [
    {
      Currencyname: 'India - Indian rupee',
      Currencycode: 'INR',
      Currencysymbol: '₹',
      isSelected: false,
      isStatus: true,
    },
    {
      Currencyname: 'US dollar	',
      Currencycode: 'USD',
      Currencysymbol: '$',
      isSelected: false,
      isStatus: true,
    },
  ];
  public groupPermission = [
    {
      Role: 'Admin',
      description: 'Owner',
      Status: 'Active',
      isSelected: false,
    },
    {
      Role: 'Purchase',
      description: 'Purchase Permission',
      Status: 'Active',
      isSelected: false,
    },
    {
      Role: 'Sales',
      description: 'Sales Permission',
      Status: 'Active',
      isSelected: false,
    },
  ];
  public taxRates = [
    {
      Taxname: 'SGST 9%',
      Tax: '9.00',
      isSelected: false,
      isStatus: true,
    },
    {
      Taxname: 'ISGT 9%',
      Tax: '9.00',
      isSelected: false,
      isStatus: true,
    },
    {
      Taxname: 'IGST 4.5%',
      Tax: '4.50',
      isSelected: false,
      isStatus: false,
    },
    {
      Taxname: 'SGST 4.5%',
      Tax: '4.50',
      isSelected: false,
      isStatus: true,
    },
  ];
  public supplierReport1 = [
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product1.jpg',
      Productname: 'Macbook pro',
      Purchasedamount: '38698.00',
      isSelected: false,
      purchasedQTY: '1248',
      Paid: '0.00',
      balance: '38698.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product2.jpg',
      Productname: 'Orange',
      Purchasedamount: '36080.00',
      isSelected: false,
      purchasedQTY: '110',
      Paid: '0.00',
      balance: '36080.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product3.jpg',
      Productname: 'Pineapple',
      Purchasedamount: '21000.00',
      isSelected: false,
      purchasedQTY: '106',
      Paid: '0.00',
      balance: '21000.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product4.jpg',
      Productname: 'Strawberry',
      Purchasedamount: '	11000.00',
      isSelected: false,
      purchasedQTY: '105',
      Paid: '0.00',
      balance: '11000.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product5.jpg',
      Productname: 'Sunglasses',
      Purchasedamount: '10100.00',
      isSelected: false,
      purchasedQTY: '100',
      Paid: '0.00',
      balance: '10600.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product6.jpg',
      Productname: 'Unpaired gray',
      Purchasedamount: '1210.00',
      isSelected: false,
      purchasedQTY: '105',
      Paid: '0.00',
      balance: '12100.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product7.jpg',
      Productname: 'Avocat',
      Purchasedamount: '4500.00',
      isSelected: false,
      purchasedQTY: '41',
      Paid: '0.00',
      balance: '4500.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product8.jpg',
      Productname: 'Banana',
      Purchasedamount: '900.00',
      isSelected: false,
      purchasedQTY: '28',
      Paid: '0.00',
      balance: '900.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product9.jpg',
      Productname: 'Earphones',
      Purchasedamount: '500.00',
      isSelected: false,
      purchasedQTY: '28',
      Paid: '0.00',
      balance: '500.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product10.jpg',
      Productname: 'Limon',
      Purchasedamount: '1500.00',
      isSelected: false,
      purchasedQTY: '28',
      Paid: '0.00',
      balance: '500.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product8.jpg',
      Productname: 'Banana',
      Purchasedamount: '900.00',
      isSelected: false,
      purchasedQTY: '28',
      Paid: '0.00',
      balance: '900.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product9.jpg',
      Productname: 'Earphones',
      Purchasedamount: '500.00',
      isSelected: false,
      purchasedQTY: '28',
      Paid: '0.00',
      balance: '500.00',
      Status: 'Received',
    },
    {
      purchasedDate: '07/12/2021 06:58:25',
      img: 'assets/img/product/product10.jpg',
      Productname: 'Limon',
      Purchasedamount: '1500.00',
      isSelected: false,
      purchasedQTY: '28',
      Paid: '0.00',
      balance: '500.00',
      Status: 'Received',
    },
  ];
  public supplierReport2 = [
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1001',
      Reference: 'INV/PR_1001',
      Suppliername: 'Thomas21',
      isSelected: false,
      Amount: '1500.00',
      Paid: '1500.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1002',
      Reference: 'INV/PR_1002',
      Suppliername: '504Benjamin',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1003',
      Reference: 'INV/PR_1003',
      Suppliername: 'James 524	',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1004',
      Reference: 'INV/PR_1004',
      Suppliername: 'Bruklin2022		',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1005',
      Reference: 'INV/PR_1005',
      Suppliername: 'BeverlyWIN25	',
      isSelected: false,
      Amount: '150.00',
      Paid: '150.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1006',
      Reference: 'INV/PR_1006',
      Suppliername: 'BHR256	',
      isSelected: false,
      Amount: '100.00',
      Paid: '100.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1007',
      Reference: 'INV/PR_1007',
      Suppliername: 'Alwin243	',
      isSelected: false,
      Amount: '5.00',
      Paid: '5.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1008',
      Reference: 'INV/PR_1008',
      Suppliername: 'FredJ25	',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1009',
      Reference: 'INV/PR_1009',
      Suppliername: 'Cras56	',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1010',
      Reference: 'INV/PR_1010',
      Suppliername: 'Cras56	',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1011',
      Reference: 'INV/PR_1011',
      Suppliername: 'FredJ25	',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1012',
      Reference: 'INV/PR_1012',
      Suppliername: 'Cras56	',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      paidby: 'Cash',
    },
    {
      DATE: '2022-03-10',
      Purchase: 'PR_1013',
      Reference: 'INV/PR_1013',
      Suppliername: 'Cras56	',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      paidby: 'Cash',
    },
  ];
  public supplierReport3 = [
    {
      Reference: 'RT_1001',
      Suppliername: 'Thomas21',
      isSelected: false,
      Amount: '1500.00',
      Paid: '1500.00',
      Amountdue: '1500.00',
      Status: 'Completed',
      PaymentStatus: 'Paid',
    },
    {
      Reference: 'RT_1002',
      Suppliername: '504Benjamin',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'Overdue',
    },
    {
      Reference: 'RT_1003',
      Suppliername: 'James 524',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'Overdue',
    },
    {
      Reference: 'RT_1004',
      Suppliername: 'Bruklin2022',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'Paid',
    },
    {
      Reference: 'RT_1005',
      Suppliername: 'BeverlyWIN25',
      isSelected: false,
      Amount: '150.00',
      Paid: '150.00',
      Amountdue: '150.00',
      Status: 'Completed',
      PaymentStatus: 'Overdue',
    },
    {
      Reference: 'RT_1006',
      Suppliername: 'BHR256',
      isSelected: false,
      Amount: '100.00',
      Paid: '100.00',
      Amountdue: '100.00',
      Status: 'Completed',
      PaymentStatus: 'Overdue',
    },
    {
      Reference: 'RT_1007',
      Suppliername: 'Alwin243',
      isSelected: false,
      Amount: '5.00',
      Paid: '5.00',
      Amountdue: '5.00',
      Status: 'Completed',
      PaymentStatus: 'Paid',
    },
    {
      Reference: 'RT_1008',
      Suppliername: 'FredJ25',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'Unpaid',
    },
    {
      Reference: 'RT_1009',
      Suppliername: 'FredJ25',
      isSelected: false,
      Amount: '10.00',
      Paid: '10.00',
      Amountdue: '10.00',
      Status: 'Completed',
      PaymentStatus: 'Unpaid',
    },
    {
      Reference: 'RT_1010',
      Suppliername: 'Cras56',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      Amountdue: '15.00',
      Status: 'Completed',
      PaymentStatus: 'Unpaid',
    },
    {
      Reference: 'RT_1010',
      Suppliername: 'Grace2022',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      Amountdue: '15.00',
      Status: 'Completed',
      PaymentStatus: 'Unpaid',
    },
    {
      Reference: 'RT_1011',
      Suppliername: 'Cras56',
      isSelected: false,
      Amount: '15.00',
      Paid: '15.00',
      Amountdue: '15.00',
      Status: 'Completed',
      PaymentStatus: 'Unpaid',
    },
    {
      Reference: 'RT_1012',
      Suppliername: 'Grace2022',
      Amount: '15.00',
      Paid: '15.00',
      Amountdue: '15.00',
      Status: 'Completed',
      PaymentStatus: 'Unpaid',
    },
  ];
  public salesListModal = [
    {
      Date: '2022-03-07',
      Reference: 'INV/SL0101',
      Amount: '$ 0.00',
      PaidBy: 'Cash',
    },
  ];
  public pos1 = [
    {
      Date: '2022-03-07',
      Reference: 'INV/SL0101',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: 'INV/SL0101',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: 'INV/SL0101',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: 'INV/SL0101',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: 'INV/SL0101',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: 'INV/SL0101',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: 'INV/SL0101',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
  ];
  public pos2 = [
    {
      Date: '2022-03-07',
      Reference: '0101',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0102',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0103',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0104',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0105',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0106',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0107',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
  ];
  public pos3 = [
    {
      Date: '2022-03-07',
      Reference: '0101',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0102',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0103',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0104',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0105',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0106',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
    {
      Date: '2022-03-07',
      Reference: '0107',
      Customer: 'Walk-in Customer',
      Amount: '$ 1500.00',
    },
  ];

  public editpermisssion = [
    {
      Name: 'Users Mangement',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      ViewAllRecords: false,
      details: [
        'View',
        'Create',
        'Edit',
        'Delete',
        'View all records of all users',
        'Select All',
      ],
    },
    {
      Name: 'User Permission',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Products',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: [
        'View',
        'Create',
        'Edit',
        'Delete',
        'Barcode',
        'Import Products',
        'Select All',
      ],
    },
    {
      Name: 'Adjustment',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Transfer',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Expenses',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Sales',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Purchase',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Quotations',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Sales Return',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Purchase Return',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Payment Sales',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Payments purchase',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Payments Return',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Customer list',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Supplier List',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
    {
      Name: 'Reports',
      View: false,
      SelectAll:false,
      Create: false,
      Edit: false,
      Delete: false,
      Barcode: false,
      ImportProducts: false,
      details: ['View', 'Create', 'Edit', 'Delete', 'Select All'],
    },
  ];
}
